services:
  db:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app

  api:
    build: ./app/backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/test_db
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app/backend:/app
    depends_on:
      - db
    restart: always
    networks:
      - app

  streamlit:
    build: ./app/frontend
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app
    depends_on:
      - api
    restart: always
    networks:
      - app

volumes:
  db_data:

networks:
  app:
    driver: bridge